apiVersion: v1
kind: Secret
metadata:
  name: ${DWT_S3_SECRET_NAME}
  labels:
    app.kubernetes.io/name: ${DWT_APP_NAME}
    app.kubernetes.io/part-of: ${DWT_PART_OF_LABEL}
    app.kubernetes.io/component: ${DWT_COMPONENT_METASTORE}
    exp.openshift.io/area: ${DWT_LABEL_AREA}
  annotations:
    openshift.io/display-name: NetApp S3 Access Credentials
    openshift.io/description: |
      Provide the NetApp StorageGRID S3 credentials and connection metadata used
      by the Hive metastore to talk to the object storage warehouse. Replace the
      placeholder values with your actual access key, secret key, and endpoint
      before applying the manifest.
type: Opaque
stringData:
  accessKey: ${DWT_S3_ACCESS_KEY}
  secretKey: ${DWT_S3_SECRET_KEY}
  region: ${DWT_S3_REGION}
  endpoint: ${DWT_S3_ENDPOINT}
  bucket: ${DWT_S3_BUCKET}
