apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dwhtrans-catalog-db
  labels:
    app.kubernetes.io/name: dwhtrans-catalog
    app.kubernetes.io/part-of: dwhtrans-catalog
    app.kubernetes.io/component: database
    exp.openshift.io/area: hive-catalog
spec:
  serviceName: dwhtrans-catalog-db
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dwhtrans-catalog
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dwhtrans-catalog
        app.kubernetes.io/part-of: dwhtrans-catalog
        app.kubernetes.io/component: database
        exp.openshift.io/area: hive-catalog
    spec:
      serviceAccountName: dwhtrans-catalog-serviceaccount
      containers:
        - name: postgres
          image: registry.redhat.io/rhel9/postgresql-15:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: dwhtrans-catalog-db
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dwhtrans-catalog-db
                  key: password
            - name: POSTGRESQL_DATABASE
              value: metastore
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgsql/data
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: dwhtrans-catalog
          app.kubernetes.io/part-of: dwhtrans-catalog
          app.kubernetes.io/component: database
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: managed-csi
---
apiVersion: v1
kind: Service
metadata:
  name: dwhtrans-catalog-db
  labels:
    app.kubernetes.io/name: dwhtrans-catalog
    app.kubernetes.io/part-of: dwhtrans-catalog
    app.kubernetes.io/component: database
    exp.openshift.io/area: hive-catalog
spec:
  selector:
    app.kubernetes.io/name: dwhtrans-catalog
    app.kubernetes.io/component: database
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  type: ClusterIP
