apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${DWT_SCHEMA_LOADER_PVC_NAME}
  labels:
    app.kubernetes.io/name: ${DWT_APP_NAME}
    app.kubernetes.io/part-of: ${DWT_PART_OF_LABEL}
    app.kubernetes.io/component: ${DWT_COMPONENT_SCHEMA_LOADER}
    exp.openshift.io/area: ${DWT_LABEL_AREA}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${DWT_SCHEMA_LOADER_STORAGE_SIZE}
