apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${DWT_SERVICE_ACCOUNT_NAME}
  labels:
    app.kubernetes.io/name: ${DWT_APP_NAME}
    app.kubernetes.io/part-of: ${DWT_PART_OF_LABEL}
    app.kubernetes.io/component: ${DWT_COMPONENT_METASTORE}
    exp.openshift.io/area: ${DWT_LABEL_AREA}
