apiVersion: v1
kind: Pod
metadata:
  name: alpine-nettest
spec:
  restartPolicy: Never
  containers:
    - name: alpine
      image: alpine:latest
      command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache iputils busybox-extras && \
          sleep infinity
