nameReference:
  - kind: ServiceAccount
    fieldSpecs:
      - kind: Deployment
        path: spec/template/spec/serviceAccountName
  - kind: Secret
    fieldSpecs:
      - kind: Deployment
        path: spec/template/spec/containers[]/envFrom[]/secretRef/name
      - kind: Deployment
        path: spec/template/spec/volumes[]/secret/secretName
  - kind: ConfigMap
    fieldSpecs:
      - kind: Deployment
        path: spec/template/spec/containers[]/envFrom[]/configMapRef/name
      - kind: Deployment
        path: spec/template/spec/volumes[]/configMap/name
