apiVersion: v1
kind: Pod
metadata:
  name: alpine-nettest
spec:
  restartPolicy: Never
  containers:
    - name: alpine
      image: alpine:latest
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache \
            --repository http://dl-cdn.alpinelinux.org/alpine/latest-stable/main \
            --repository http://dl-cdn.alpinelinux.org/alpine/latest-stable/community \
            iputils busybox-extras curl && \
          sleep infinity
